// DO NOT EDIT THIS FILE - it is machine generated
#ifndef SPL_JNIFunctions_com_ibm_iot4i_examples_h
#define SPL_JNIFunctions_com_ibm_iot4i_examples_h

#include <SPL/Runtime/Function/SPLJavaFunction.h>
#include <SPL/Runtime/Type/SPLType.h>

namespace SPL {
namespace JNIFunctions {
namespace com {
namespace ibm {
namespace iot4i {
namespace examples {
class SPL_JNIFunctions {
public:

// Generated from com.ibm.iot4i.examples.EventEntryConditionImpl in impl/java/bin/com/ibm/iot4i/examples/EventEntryConditionImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::boolean eventEntryCondition(SPL::ustring const & arg1) {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("SevereWeatherShield", "1.0.0", SPLJAVAFUNCTION_ADL_FILENAME, "impl/java/bin", "com.ibm.iot4i.examples.EventEntryConditionImpl", "eventEntryCondition", "(Ljava/lang/String;)Z", "com.ibm.iot4i.examples", "<string T> public boolean eventEntryCondition(T message)", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    jstring obj1 = env->NewString((jchar *) arg1.getBuffer(), (jsize) arg1.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    SPL::boolean result = env->CallStaticBooleanMethod(classGlobalRef, mid, obj1);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    env->DeleteLocalRef(obj1);
    return result;
}

// Generated from com.ibm.iot4i.examples.EventEntryConditionImpl in impl/java/bin/com/ibm/iot4i/examples/EventEntryConditionImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::boolean eventEntryCondition(SPL::rstring const & arg1) {
    SPL::boolean result = eventEntryCondition(SPL::ustring::fromUTF8(arg1));
    return result;
}

// Generated from com.ibm.iot4i.examples.EventEntryConditionImpl in impl/java/bin/com/ibm/iot4i/examples/EventEntryConditionImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
template <SPL::int32 msize>
static SPL::boolean eventEntryCondition(SPL::bstring<msize> const & arg1) {
    SPL::boolean result = eventEntryCondition((SPL::rstring) arg1);
    return result;
}

// Generated from com.ibm.iot4i.examples.GetLocationAsWKTImpl in impl/java/bin/com/ibm/iot4i/examples/GetLocationAsWKTImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::ustring getLocationAsWKT(SPL::ustring const & arg1, SPL::boolean const & arg2) {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("SevereWeatherShield", "1.0.0", SPLJAVAFUNCTION_ADL_FILENAME, "impl/java/bin", "com.ibm.iot4i.examples.GetLocationAsWKTImpl", "getLocationAsWKT", "(Ljava/lang/String;Z)Ljava/lang/String;", "com.ibm.iot4i.examples", "<string T> public T getLocationAsWKT(T message, boolean isSensorEvent)", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    jstring obj1 = env->NewString((jchar *) arg1.getBuffer(), (jsize) arg1.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    jstring resObj = (jstring) env->CallStaticObjectMethod(classGlobalRef, mid, obj1, (jboolean) arg2);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    env->DeleteLocalRef(obj1);
    if (resObj != NULL) {
        const jchar *chars = env->GetStringChars(resObj, NULL);
        if (chars == NULL)
            SPL::SPLJavaFunction::throwCreateError(func);
        SPL::ustring result((const UChar *) chars, (int32_t) env->GetStringLength(resObj));
        env->ReleaseStringChars(resObj, chars);
        env->DeleteLocalRef(resObj);
        return result;
    } else {
        return SPL::ustring::fromUTF8("");
    }
}

// Generated from com.ibm.iot4i.examples.GetLocationAsWKTImpl in impl/java/bin/com/ibm/iot4i/examples/GetLocationAsWKTImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::rstring getLocationAsWKT(SPL::rstring const & arg1, SPL::boolean const & arg2) {
    SPL::ustring result = getLocationAsWKT(SPL::ustring::fromUTF8(arg1), arg2);
    return SPL::ustring::toUTF8(result);
}

// Generated from com.ibm.iot4i.examples.GetLocationAsWKTImpl in impl/java/bin/com/ibm/iot4i/examples/GetLocationAsWKTImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
template <SPL::int32 msize>
static SPL::bstring<msize> getLocationAsWKT(SPL::bstring<msize> const & arg1, SPL::boolean const & arg2) {
    SPL::rstring result = getLocationAsWKT((SPL::rstring) arg1, arg2);
    return (SPL::bstring<msize>) result;
}

// Generated from com.ibm.iot4i.examples.GetTemperatureImpl in impl/java/bin/com/ibm/iot4i/examples/GetTemperatureImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::int32 getTemperature(SPL::ustring const & arg1) {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("SevereWeatherShield", "1.0.0", SPLJAVAFUNCTION_ADL_FILENAME, "impl/java/bin", "com.ibm.iot4i.examples.GetTemperatureImpl", "getTemperature", "(Ljava/lang/String;)I", "com.ibm.iot4i.examples", "<string T> public int32 getTemperature(T message)", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    jstring obj1 = env->NewString((jchar *) arg1.getBuffer(), (jsize) arg1.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    SPL::int32 result = env->CallStaticIntMethod(classGlobalRef, mid, obj1);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    env->DeleteLocalRef(obj1);
    return result;
}

// Generated from com.ibm.iot4i.examples.GetTemperatureImpl in impl/java/bin/com/ibm/iot4i/examples/GetTemperatureImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::int32 getTemperature(SPL::rstring const & arg1) {
    SPL::int32 result = getTemperature(SPL::ustring::fromUTF8(arg1));
    return result;
}

// Generated from com.ibm.iot4i.examples.GetTemperatureImpl in impl/java/bin/com/ibm/iot4i/examples/GetTemperatureImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
template <SPL::int32 msize>
static SPL::int32 getTemperature(SPL::bstring<msize> const & arg1) {
    SPL::int32 result = getTemperature((SPL::rstring) arg1);
    return result;
}

// Generated from com.ibm.iot4i.examples.GetZipCodeImpl in impl/java/bin/com/ibm/iot4i/examples/GetZipCodeImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::ustring getZipCode(SPL::ustring const & arg1) {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("SevereWeatherShield", "1.0.0", SPLJAVAFUNCTION_ADL_FILENAME, "impl/java/bin", "com.ibm.iot4i.examples.GetZipCodeImpl", "getZipCode", "(Ljava/lang/String;)Ljava/lang/String;", "com.ibm.iot4i.examples", "<string T> public T getZipCode(T message)", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    jstring obj1 = env->NewString((jchar *) arg1.getBuffer(), (jsize) arg1.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    jstring resObj = (jstring) env->CallStaticObjectMethod(classGlobalRef, mid, obj1);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    env->DeleteLocalRef(obj1);
    if (resObj != NULL) {
        const jchar *chars = env->GetStringChars(resObj, NULL);
        if (chars == NULL)
            SPL::SPLJavaFunction::throwCreateError(func);
        SPL::ustring result((const UChar *) chars, (int32_t) env->GetStringLength(resObj));
        env->ReleaseStringChars(resObj, chars);
        env->DeleteLocalRef(resObj);
        return result;
    } else {
        return SPL::ustring::fromUTF8("");
    }
}

// Generated from com.ibm.iot4i.examples.GetZipCodeImpl in impl/java/bin/com/ibm/iot4i/examples/GetZipCodeImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::rstring getZipCode(SPL::rstring const & arg1) {
    SPL::ustring result = getZipCode(SPL::ustring::fromUTF8(arg1));
    return SPL::ustring::toUTF8(result);
}

// Generated from com.ibm.iot4i.examples.GetZipCodeImpl in impl/java/bin/com/ibm/iot4i/examples/GetZipCodeImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
template <SPL::int32 msize>
static SPL::bstring<msize> getZipCode(SPL::bstring<msize> const & arg1) {
    SPL::rstring result = getZipCode((SPL::rstring) arg1);
    return (SPL::bstring<msize>) result;
}

// Generated from com.ibm.iot4i.examples.WeatherEntryConditionImpl in impl/java/bin/com/ibm/iot4i/examples/WeatherEntryConditionImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::boolean weatherEntryCondition(SPL::ustring const & arg1) {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("SevereWeatherShield", "1.0.0", SPLJAVAFUNCTION_ADL_FILENAME, "impl/java/bin", "com.ibm.iot4i.examples.WeatherEntryConditionImpl", "weatherEntryCondition", "(Ljava/lang/String;)Z", "com.ibm.iot4i.examples", "<string T> public boolean weatherEntryCondition(T message)", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    jstring obj1 = env->NewString((jchar *) arg1.getBuffer(), (jsize) arg1.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    SPL::boolean result = env->CallStaticBooleanMethod(classGlobalRef, mid, obj1);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    env->DeleteLocalRef(obj1);
    return result;
}

// Generated from com.ibm.iot4i.examples.WeatherEntryConditionImpl in impl/java/bin/com/ibm/iot4i/examples/WeatherEntryConditionImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
static SPL::boolean weatherEntryCondition(SPL::rstring const & arg1) {
    SPL::boolean result = weatherEntryCondition(SPL::ustring::fromUTF8(arg1));
    return result;
}

// Generated from com.ibm.iot4i.examples.WeatherEntryConditionImpl in impl/java/bin/com/ibm/iot4i/examples/WeatherEntryConditionImpl$StreamsModel.class at Wed Sep 20 11:38:38 EDT 2017
template <SPL::int32 msize>
static SPL::boolean weatherEntryCondition(SPL::bstring<msize> const & arg1) {
    SPL::boolean result = weatherEntryCondition((SPL::rstring) arg1);
    return result;
}

};
}
}
}
}
}
}
#endif
